laravel/app/routes.php
<?php

// Front-end

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

Route::get('escritorio/{slug?}', ['as' => 'escritorio', 'uses' => 'EscritorioController@index']);
Route::get('atuacao/{slug?}', ['as' => 'atuacao', 'uses' => 'AtuacaoController@index']);
Route::get('equipe/{id?}', ['as' => 'equipe', 'uses' => 'EquipeController@index']);

Route::get('noticias/equipe/{id}', ['as' => 'noticias.equipe', 'uses' => 'NoticiasController@equipe']);
Route::get('noticias/{slug?}', ['as' => 'noticias', 'uses' => 'NoticiasController@index']);

Route::get('corporativo/equipe/{id}', ['as' => 'corporativo.equipe', 'uses' => 'CorporativoController@equipe']);
Route::get('corporativo/{slug?}', ['as' => 'corporativo', 'uses' => 'CorporativoController@index']);

Route::get('contato', ['as' => 'contato', 'uses' => 'ContatoController@index']);
Route::post('contato', ['as' => 'contato.envio', 'uses' => 'ContatoController@envio']);

Route::any('busca', ['as' => 'busca', 'uses' => 'BuscaController@index']);


// Idiomas

Route::get('idioma/{sigla_idioma?}', ['as' => 'idioma', function($sigla_idioma){
    if ($sigla_idioma == 'pt' || $sigla_idioma == 'es' || $sigla_idioma == 'en') {
        Session::put('locale', $sigla_idioma);
    }

    return Redirect::to(URL::previous());
}]);


// Painel

Route::get('painel', [
    'before' => 'auth',
    'as'     => 'painel.home',
    'uses'   => 'Painel\HomeController@index'
]);

Route::get('painel/login', [
    'as'   => 'painel.login',
    'uses' => 'Painel\HomeController@login'
]);
Route::post('painel/login', [
    'as'   => 'painel.auth',
    'uses' => 'Painel\HomeController@attempt'
]);
Route::get('painel/logout', [
    'as'   => 'painel.logout',
    'uses' => 'Painel\HomeController@logout'
]);

Route::group(['prefix' => 'painel', 'before' => 'auth'], function() {
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    Route::resource('banners', 'Painel\BannersController');
    Route::resource('escritorio', 'Painel\EscritorioController');

    Route::resource('atuacao/pratica', 'Painel\PraticaController');
    Route::resource('atuacao/fazemos', 'Painel\FazemosController');
    Route::resource('atuacao', 'Painel\AtuacaoController');

    Route::resource('equipe', 'Painel\EquipeController');

    Route::resource('noticias/corporativo', 'Painel\CorporativoController');
    Route::resource('noticias', 'Painel\NoticiasController');

    Route::resource('contato/recebidos', 'Painel\ContatosRecebidosController');
    Route::resource('contato', 'Painel\ContatoController');

    Route::resource('usuarios', 'Painel\UsuariosController');

    Route::post('ajax/order', 'Painel\AjaxController@order');
    Route::post('ckeditor-upload', 'Painel\AjaxController@imageUpload');
});

laravel/app/controllers/painel/AjaxController.php
<?php

namespace Painel;

use \Request, \Input, \DB, \Controller, \CropImage;

class AjaxController extends Controller {

    private $image_config = [
        'width'  => 800,
        'height' => null,
        'upsize' => true,
        'path'   => 'assets/img/noticias/'
    ];

    function order()
    {

        if (!Request::ajax()) return false;

        $menu   = Input::get('data');
        $tabela = Input::get('tabela');

        for ($i = 0; $i < count($menu); $i++) {
            DB::table($tabela)->where('id', $menu[$i])->update(array('ordem' => $i));
        }

        return json_encode($menu);

    }

    public function imageUpload()
    {
        $validator = \Validator::make(Request::all(), [
            'imagem' => 'image|required'
        ]);

        if ($validator->fails()) {
            $response = [
                'error'   => true,
                'message' => 'O arquivo deve ser uma imagem.'
            ];
        } else {
            $imagem   = CropImage::make('imagem', $this->image_config);
            $response = [
                'filepath' => asset($this->image_config['path'] . $imagem)
            ];
        }

        return $response;
    }
}

laravel/app/controllers/painel/AtuacaoController.php
<?php

namespace Painel;

use \Atuacao, \Input, \Session, \Redirect, \Validator;

class AtuacaoController extends BasePainelController {

    private $validation_rules = [
        'texto_pt' => 'required',
        'texto_en' => 'required',
        'texto_es' => 'required'
    ];

    public function index()
    {
    	$atuacao = Atuacao::first();

        return $this->view('painel.atuacao.index', compact('atuacao'));
    }

    public function update($id)
    {
        $atuacao = Atuacao::findOrFail($id);
        $input   = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $atuacao->update($input);
            Session::flash('sucesso', 'Página alterada com sucesso.');

            return Redirect::route('painel.atuacao.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar página.'])
                ->withInput();

        }
    }

}

laravel/app/controllers/painel/BannersController.php
<?php

namespace Painel;

use \Banner, \Input, \Validator, \Redirect, \Session, \CropImage;

class BannersController extends BasePainelController {

    private $validation_rules = [
        'imagem'       => 'required|image',
        'cor'          => 'required',
        'link'         => 'required',
        'titulo_pt'    => 'required',
        'titulo_en'    => 'required',
        'titulo_es'    => 'required',
        'texto_pt'     => 'required',
        'texto_en'     => 'required',
        'texto_es'     => 'required',
    ];

    private $image_config = [
        'width'  => 1024,
        'height' => 380,
        'path'   => 'assets/img/banners/'
    ];

    public function index()
    {
        $banners = Banner::ordenados()->get();

        return $this->view('painel.banners.index', compact('banners'));
    }

    public function create()
    {
        return $this->view('painel.banners.create');
    }

    public function store()
    {
        $input = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['imagem'] = CropImage::make('imagem', $this->image_config);
            Banner::create($input);
            Session::flash('sucesso', 'Banner adicionado com sucesso.');

            return Redirect::route('painel.banners.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao criar banner.'])
                ->withInput();

        }
    }

    public function edit($id)
    {
        $banner = Banner::findOrFail($id);

        return $this->view('painel.banners.edit', compact('banner'));
    }

    public function update($id)
    {
        $banner = Banner::findOrFail($id);
        $input  = Input::all();

        $this->validation_rules['imagem'] = 'image';
        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            if (Input::hasFile('imagem')) {
                $input['imagem'] = CropImage::make('imagem', $this->image_config);
            } else {
                unset($input['imagem']);
            }

            $banner->update($input);
            Session::flash('sucesso', 'Banner alterado com sucesso.');

            return Redirect::route('painel.banners.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar banner.'])
                ->withInput();

        }
    }

    public function destroy($id)
    {
        try {

            Banner::destroy($id);
            Session::flash('sucesso', 'Banner removido com sucesso.');

            return Redirect::route('painel.banners.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover banner.']);

        }
    }

}

laravel/app/controllers/painel/BasePainelController.php
<?php

namespace Painel;

use \View, \ContatoRecebido;

class BasePainelController extends \Controller {

    protected $layout = 'painel.common.template';

    protected function setupLayout()
    {
        if ( ! is_null($this->layout))
        {
            $recebidos_count = ContatoRecebido::naoLidos()->count();
            View::share(compact('recebidos_count'));
            $this->layout = View::make($this->layout);
        }
    }

    protected function view($path, array $data = [])
    {
        $this->layout->content = View::make($path, $data);
    }

}

laravel/app/controllers/painel/ContatoController.php
<?php

namespace Painel;

use \Contato, \Input, \Session, \Redirect, \Validator;

class ContatoController extends BasePainelController {

    private $validation_rules = [
        'email' => 'required|email'
    ];

    public function index()
    {
    	$contato = Contato::first();

        return $this->view('painel.contato.index', compact('contato'));
    }

    public function update($id)
    {
        $contato = Contato::findOrFail($id);
        $input   = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $contato->update($input);
            Session::flash('sucesso', 'Informações de contato alteradas com sucesso.');

            return Redirect::route('painel.contato.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar informações de contato.'])
                ->withInput();

        }
    }

}

laravel/app/controllers/painel/ContatosRecebidosController.php
<?php

namespace Painel;

use \ContatoRecebido, \Session, \Redirect;

class ContatosRecebidosController extends BasePainelController {

    public function index()
    {
        $contatos_recebidos = ContatoRecebido::all();

        return $this->view('painel.contatosrecebidos.index', compact('contatos_recebidos'));
    }

    public function show($id)
    {
        $contato = ContatoRecebido::findOrFail($id);
        $contato->update(['lido' => 'true']);

        return $this->view('painel.contatosrecebidos.show', compact('contato'));
    }

    public function destroy($id)
    {
        try {

            ContatoRecebido::destroy($id);
            Session::flash('sucesso', 'Mensagem removida com sucesso.');

            return Redirect::route('painel.contato.recebidos.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover mensagem.']);

        }
    }

}

laravel/app/controllers/painel/CorporativoController.php
<?php

namespace Painel;

use \Corporativo, \Equipe, \Input, \Validator, \Redirect, \Session, \Str;

class CorporativoController extends BasePainelController {

    private $validation_rules = [
        'data'   => 'required',
        'idioma' => 'required',
        'titulo' => 'required',
        'texto'  => 'required',
    ];

    public function index()
    {
        $idioma = Input::get('idioma');
        if(!Input::has('idioma') || ($idioma != 'pt' && $idioma != 'en' && $idioma != 'es'))
            $idioma = 'pt';

        $noticias = Corporativo::idioma($idioma)->ordenados()->paginate(10);

        return $this->view('painel.corporativo.index', compact('noticias', 'idioma'));
    }

    public function create()
    {
        $equipe = Equipe::lists('nome', 'id');

        return $this->view('painel.corporativo.create', compact('equipe'));
    }

    public function store()
    {
        $input = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['slug'] = Str::slug(Input::get('titulo'));

            Corporativo::create($input);
            Session::flash('sucesso', 'Notícia adicionada com sucesso.');

            return Redirect::route('painel.noticias.corporativo.index', ['idioma' => $input['idioma']]);

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao criar notícia. Verifique se já existe outra notícia com o mesmo título.'])
                ->withInput();

        }
    }

    public function edit($id)
    {
        $noticia = Corporativo::findOrFail($id);
        $equipe  = Equipe::lists('nome', 'id');

        return $this->view('painel.corporativo.edit', compact('noticia', 'equipe'));
    }

    public function update($id)
    {
        $noticia = Corporativo::findOrFail($id);
        $input   = Input::all();

        $input['slug'] = Str::slug(Input::get('titulo'));

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $noticia->update($input);
            Session::flash('sucesso', 'Notícia alterada com sucesso.');

            return Redirect::route('painel.noticias.corporativo.index', ['idioma' => $input['idioma']]);

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar notícia.'])
                ->withInput();

        }
    }

    public function destroy($id)
    {
        try {

            $idioma = Corporativo::find($id)->idioma;
            Corporativo::destroy($id);
            Session::flash('sucesso', 'Notícia removida com sucesso.');

            return Redirect::route('painel.noticias.corporativo.index', ['idioma' => $idioma]);

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover notícia.']);

        }
    }

}

laravel/app/controllers/painel/EquipeController.php
<?php

namespace Painel;

use \Equipe, \Input, \Validator, \Redirect, \Session, \CropImage;

class EquipeController extends BasePainelController {

    private $validation_rules = [
        'nome'     => 'required',
        'email'    => 'email',
        'cargo_pt' => 'required',
        'cargo_en' => 'required',
        'cargo_es' => 'required',
        'texto_pt' => 'required',
        'texto_en' => 'required',
        'texto_es' => 'required',
    ];

    private $image_config = [
        'width'  => 294,
        'height' => 360,
        'path'   => 'assets/img/equipe/'
    ];

    public function index()
    {
        $equipe = Equipe::ordenados()->get();

        return $this->view('painel.equipe.index', compact('equipe'));
    }

    public function create()
    {
        return $this->view('painel.equipe.create');
    }

    public function store()
    {
        $input = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['imagem'] = CropImage::make('imagem', $this->image_config);
            Equipe::create($input);
            Session::flash('sucesso', 'Registro adicionado com sucesso.');

            return Redirect::route('painel.equipe.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao criar registro.'])
                ->withInput();

        }
    }

    public function edit($id)
    {
        $equipe = Equipe::findOrFail($id);

        return $this->view('painel.equipe.edit', compact('equipe'));
    }

    public function update($id)
    {
        $equipe = Equipe::findOrFail($id);
        $input  = Input::all();

        $this->validation_rules['imagem'] = 'image';
        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            if (Input::hasFile('imagem')) {
                $input['imagem'] = CropImage::make('imagem', $this->image_config);
            } else {
                unset($input['imagem']);
            }

            $equipe->update($input);
            Session::flash('sucesso', 'Registro alterado com sucesso.');

            return Redirect::route('painel.equipe.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar registro.'])
                ->withInput();

        }
    }

    public function destroy($id)
    {
        try {

            Equipe::destroy($id);
            Session::flash('sucesso', 'Registro removido com sucesso.');

            return Redirect::route('painel.equipe.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover registro.']);

        }
    }

}

laravel/app/views/painel/common/nav.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url() }}">{{ Config::get('projeto.name') }}</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li @if(str_is('painel.banners*', Route::currentRouteName())) class="active" @endif>
                    <a href="{{ route('painel.banners.index') }}">Banners</a>
                </li>

                <li @if(str_is('painel.escritorio*', Route::currentRouteName())) class="active" @endif>
                    <a href="{{ route('painel.escritorio.index') }}">Escritório</a>
                </li>

                <li class="dropdown @if(str_is('painel.atuacao*', Route::currentRouteName())) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Atuação <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ route('painel.atuacao.index') }}">Atuação</a></li>
                        <li><a href="{{ route('painel.atuacao.pratica.index') }}">Prática Legal</a></li>
                        <li><a href="{{ route('painel.atuacao.fazemos.index') }}">O que fazemos para</a></li>
                    </ul>
                </li>

                <li @if(str_is('painel.equipe*', Route::currentRouteName())) class="active" @endif>
                    <a href="{{ route('painel.equipe.index') }}">Equipe</a>
                </li>

                <li class="dropdown @if(str_is('painel.noticias*', Route::currentRouteName())) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Notícias <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ route('painel.noticias.index') }}">Notícias</a></li>
                        <li><a href="{{ route('painel.noticias.corporativo.index') }}">Corporativo</a></li>
                    </ul>
                </li>

                <li class="dropdown @if(str_is('painel.contato*', Route::currentRouteName())) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Contato @if($recebidos_count>=1)<span class="badge">{{ $recebidos_count }}</span>@endif <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ route('painel.contato.index') }}">Informações de Contato</a></li>
                        <li><a href="{{ route('painel.contato.recebidos.index') }}">Contatos Recebidos @if($recebidos_count>=1)<span class="badge">{{ $recebidos_count }}</span>@endif</a></li>
                    </ul>
                </li>

                <li class="dropdown @if(str_is('painel.usuarios*', Route::currentRouteName())) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sistema <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ route('painel.usuarios.index') }}">Usuários</a></li>
                        <li><a href="{{ route('painel.logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

laravel/app/views/painel/common/template.blade.php
<?php $login = (Route::currentRouteName() == 'painel.login'); ?>
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{ Config::get('projeto.name') }} - Painel Administrativo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ asset('assets/css/painel/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/painel/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/painel/painel.min.css') }}">
    <script>var BASE = '{{ url() }}'</script>
</head>
<body class="{{ ($login ? 'login' : 'painel') }}">
    @if(!$login)
        @include('painel.common.nav')
    @endif

    <div class="{{ ($login ? 'wrapper' : 'main container') }}">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="assets/js/jquery.min.js"><\/script>')</script>
    <script src="{{ asset('assets/js/painel/vendor.min.js') }}"></script>
    <script src="{{ asset('assets/js/painel/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/js/painel/painel.js') }}"></script>
</body>
</html>