laravel/app/routes.php
<?php

// Front-end

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

Route::get('escritorio/{slug?}', ['as' => 'escritorio', 'uses' => 'EscritorioController@index']);
Route::get('atuacao/{slug?}', ['as' => 'atuacao', 'uses' => 'AtuacaoController@index']);
Route::get('equipe/{id?}', ['as' => 'equipe', 'uses' => 'EquipeController@index']);

Route::get('noticias/equipe/{id}', ['as' => 'noticias.equipe', 'uses' => 'NoticiasController@equipe']);
Route::get('noticias/{slug?}', ['as' => 'noticias', 'uses' => 'NoticiasController@index']);

Route::get('corporativo/equipe/{id}', ['as' => 'corporativo.equipe', 'uses' => 'CorporativoController@equipe']);
Route::get('corporativo/{slug?}', ['as' => 'corporativo', 'uses' => 'CorporativoController@index']);

Route::get('contato', ['as' => 'contato', 'uses' => 'ContatoController@index']);
Route::post('contato', ['as' => 'contato.envio', 'uses' => 'ContatoController@envio']);

Route::any('busca', ['as' => 'busca', 'uses' => 'BuscaController@index']);


// Idiomas

Route::get('idioma/{sigla_idioma?}', ['as' => 'idioma', function($sigla_idioma){
    if ($sigla_idioma == 'pt' || $sigla_idioma == 'es' || $sigla_idioma == 'en') {
        Session::put('locale', $sigla_idioma);
    }

    return Redirect::to(URL::previous());
}]);


// Painel

Route::get('painel', [
    'before' => 'auth',
    'as'     => 'painel.home',
    'uses'   => 'Painel\HomeController@index'
]);

Route::get('painel/login', [
    'as'   => 'painel.login',
    'uses' => 'Painel\HomeController@login'
]);
Route::post('painel/login', [
    'as'   => 'painel.auth',
    'uses' => 'Painel\HomeController@attempt'
]);
Route::get('painel/logout', [
    'as'   => 'painel.logout',
    'uses' => 'Painel\HomeController@logout'
]);

Route::group(['prefix' => 'painel', 'before' => 'auth'], function() {
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    Route::resource('banners', 'Painel\BannersController');
    Route::resource('escritorio', 'Painel\EscritorioController');

    Route::resource('atuacao/pratica', 'Painel\PraticaController');
    Route::resource('atuacao/fazemos', 'Painel\FazemosController');
    Route::resource('atuacao', 'Painel\AtuacaoController');

    Route::resource('equipe', 'Painel\EquipeController');

    Route::resource('noticias/corporativo', 'Painel\CorporativoController');
    Route::resource('noticias', 'Painel\NoticiasController');

    Route::resource('contato/recebidos', 'Painel\ContatosRecebidosController');
    Route::resource('contato', 'Painel\ContatoController');

    Route::resource('usuarios', 'Painel\UsuariosController');

    Route::post('ajax/order', 'Painel\AjaxController@order');
    Route::post('ckeditor-upload', 'Painel\AjaxController@imageUpload');
});

laravel/app/models/Pratica.php
<?php

class Pratica extends Eloquent
{

    protected $table = 'pratica';

    protected $hidden = [];

    protected $guarded = ['id'];

    public function scopeOrdenados($query)
    {
        return $query->orderBy('ordem', 'ASC');
    }

}

laravel/app/controllers/painel/AjaxController.php
<?php

namespace Painel;

use \Request, \Input, \DB, \Controller, \CropImage;

class AjaxController extends Controller {

    private $image_config = [
        'width'  => 800,
        'height' => null,
        'upsize' => true,
        'path'   => 'assets/img/noticias/'
    ];

    function order()
    {

        if (!Request::ajax()) return false;

        $menu   = Input::get('data');
        $tabela = Input::get('tabela');

        for ($i = 0; $i < count($menu); $i++) {
            DB::table($tabela)->where('id', $menu[$i])->update(array('ordem' => $i));
        }

        return json_encode($menu);

    }

    public function imageUpload()
    {
        $validator = \Validator::make(Request::all(), [
            'imagem' => 'image|required'
        ]);

        if ($validator->fails()) {
            $response = [
                'error'   => true,
                'message' => 'O arquivo deve ser uma imagem.'
            ];
        } else {
            $imagem   = CropImage::make('imagem', $this->image_config);
            $response = [
                'filepath' => asset($this->image_config['path'] . $imagem)
            ];
        }

        return $response;
    }
}

laravel/app/controllers/painel/AtuacaoController.php
<?php

namespace Painel;

use \Atuacao, \Input, \Session, \Redirect, \Validator;

class AtuacaoController extends BasePainelController {

    private $validation_rules = [
        'texto_pt' => 'required',
        'texto_en' => 'required',
        'texto_es' => 'required'
    ];

    public function index()
    {
    	$atuacao = Atuacao::first();

        return $this->view('painel.atuacao.index', compact('atuacao'));
    }

    public function update($id)
    {
        $atuacao = Atuacao::findOrFail($id);
        $input   = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $atuacao->update($input);
            Session::flash('sucesso', 'Página alterada com sucesso.');

            return Redirect::route('painel.atuacao.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar página.'])
                ->withInput();

        }
    }

}

laravel/app/controllers/painel/BannersController.php
<?php

namespace Painel;

use \Banner, \Input, \Validator, \Redirect, \Session, \CropImage;

class BannersController extends BasePainelController {

    private $validation_rules = [
        'imagem'       => 'required|image',
        'cor'          => 'required',
        'link'         => 'required',
        'titulo_pt'    => 'required',
        'titulo_en'    => 'required',
        'titulo_es'    => 'required',
        'texto_pt'     => 'required',
        'texto_en'     => 'required',
        'texto_es'     => 'required',
    ];

    private $image_config = [
        'width'  => 1024,
        'height' => 380,
        'path'   => 'assets/img/banners/'
    ];

    public function index()
    {
        $banners = Banner::ordenados()->get();

        return $this->view('painel.banners.index', compact('banners'));
    }

    public function create()
    {
        return $this->view('painel.banners.create');
    }

    public function store()
    {
        $input = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['imagem'] = CropImage::make('imagem', $this->image_config);
            Banner::create($input);
            Session::flash('sucesso', 'Banner adicionado com sucesso.');

            return Redirect::route('painel.banners.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao criar banner.'])
                ->withInput();

        }
    }

    public function edit($id)
    {
        $banner = Banner::findOrFail($id);

        return $this->view('painel.banners.edit', compact('banner'));
    }

    public function update($id)
    {
        $banner = Banner::findOrFail($id);
        $input  = Input::all();

        $this->validation_rules['imagem'] = 'image';
        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            if (Input::hasFile('imagem')) {
                $input['imagem'] = CropImage::make('imagem', $this->image_config);
            } else {
                unset($input['imagem']);
            }

            $banner->update($input);
            Session::flash('sucesso', 'Banner alterado com sucesso.');

            return Redirect::route('painel.banners.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar banner.'])
                ->withInput();

        }
    }

    public function destroy($id)
    {
        try {

            Banner::destroy($id);
            Session::flash('sucesso', 'Banner removido com sucesso.');

            return Redirect::route('painel.banners.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover banner.']);

        }
    }

}

laravel/app/controllers/painel/BasePainelController.php
<?php

namespace Painel;

use \View, \ContatoRecebido;

class BasePainelController extends \Controller {

    protected $layout = 'painel.common.template';

    protected function setupLayout()
    {
        if ( ! is_null($this->layout))
        {
            $recebidos_count = ContatoRecebido::naoLidos()->count();
            View::share(compact('recebidos_count'));
            $this->layout = View::make($this->layout);
        }
    }

    protected function view($path, array $data = [])
    {
        $this->layout->content = View::make($path, $data);
    }

}

laravel/app/controllers/painel/ContatoController.php
<?php

namespace Painel;

use \Contato, \Input, \Session, \Redirect, \Validator;

class ContatoController extends BasePainelController {

    private $validation_rules = [
        'email' => 'required|email'
    ];

    public function index()
    {
    	$contato = Contato::first();

        return $this->view('painel.contato.index', compact('contato'));
    }

    public function update($id)
    {
        $contato = Contato::findOrFail($id);
        $input   = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $contato->update($input);
            Session::flash('sucesso', 'Informações de contato alteradas com sucesso.');

            return Redirect::route('painel.contato.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar informações de contato.'])
                ->withInput();

        }
    }

}

laravel/app/controllers/painel/ContatosRecebidosController.php
<?php

namespace Painel;

use \ContatoRecebido, \Session, \Redirect;

class ContatosRecebidosController extends BasePainelController {

    public function index()
    {
        $contatos_recebidos = ContatoRecebido::all();

        return $this->view('painel.contatosrecebidos.index', compact('contatos_recebidos'));
    }

    public function show($id)
    {
        $contato = ContatoRecebido::findOrFail($id);
        $contato->update(['lido' => 'true']);

        return $this->view('painel.contatosrecebidos.show', compact('contato'));
    }

    public function destroy($id)
    {
        try {

            ContatoRecebido::destroy($id);
            Session::flash('sucesso', 'Mensagem removida com sucesso.');

            return Redirect::route('painel.contato.recebidos.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover mensagem.']);

        }
    }

}

laravel/app/controllers/painel/CorporativoController.php
<?php

namespace Painel;

use \Corporativo, \Equipe, \Input, \Validator, \Redirect, \Session, \Str;

class CorporativoController extends BasePainelController {

    private $validation_rules = [
        'data'   => 'required',
        'idioma' => 'required',
        'titulo' => 'required',
        'texto'  => 'required',
    ];

    public function index()
    {
        $idioma = Input::get('idioma');
        if(!Input::has('idioma') || ($idioma != 'pt' && $idioma != 'en' && $idioma != 'es'))
            $idioma = 'pt';

        $noticias = Corporativo::idioma($idioma)->ordenados()->paginate(10);

        return $this->view('painel.corporativo.index', compact('noticias', 'idioma'));
    }

    public function create()
    {
        $equipe = Equipe::lists('nome', 'id');

        return $this->view('painel.corporativo.create', compact('equipe'));
    }

    public function store()
    {
        $input = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['slug'] = Str::slug(Input::get('titulo'));

            Corporativo::create($input);
            Session::flash('sucesso', 'Notícia adicionada com sucesso.');

            return Redirect::route('painel.noticias.corporativo.index', ['idioma' => $input['idioma']]);

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao criar notícia. Verifique se já existe outra notícia com o mesmo título.'])
                ->withInput();

        }
    }

    public function edit($id)
    {
        $noticia = Corporativo::findOrFail($id);
        $equipe  = Equipe::lists('nome', 'id');

        return $this->view('painel.corporativo.edit', compact('noticia', 'equipe'));
    }

    public function update($id)
    {
        $noticia = Corporativo::findOrFail($id);
        $input   = Input::all();

        $input['slug'] = Str::slug(Input::get('titulo'));

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $noticia->update($input);
            Session::flash('sucesso', 'Notícia alterada com sucesso.');

            return Redirect::route('painel.noticias.corporativo.index', ['idioma' => $input['idioma']]);

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar notícia.'])
                ->withInput();

        }
    }

    public function destroy($id)
    {
        try {

            $idioma = Corporativo::find($id)->idioma;
            Corporativo::destroy($id);
            Session::flash('sucesso', 'Notícia removida com sucesso.');

            return Redirect::route('painel.noticias.corporativo.index', ['idioma' => $idioma]);

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover notícia.']);

        }
    }

}

laravel/app/controllers/painel/EquipeController.php
<?php

namespace Painel;

use \Equipe, \Input, \Validator, \Redirect, \Session, \CropImage;

class EquipeController extends BasePainelController {

    private $validation_rules = [
        'nome'     => 'required',
        'email'    => 'email',
        'cargo_pt' => 'required',
        'cargo_en' => 'required',
        'cargo_es' => 'required',
        'texto_pt' => 'required',
        'texto_en' => 'required',
        'texto_es' => 'required',
    ];

    private $image_config = [
        'width'  => 294,
        'height' => 360,
        'path'   => 'assets/img/equipe/'
    ];

    public function index()
    {
        $equipe = Equipe::ordenados()->get();

        return $this->view('painel.equipe.index', compact('equipe'));
    }

    public function create()
    {
        return $this->view('painel.equipe.create');
    }

    public function store()
    {
        $input = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['imagem'] = CropImage::make('imagem', $this->image_config);
            Equipe::create($input);
            Session::flash('sucesso', 'Registro adicionado com sucesso.');

            return Redirect::route('painel.equipe.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao criar registro.'])
                ->withInput();

        }
    }

    public function edit($id)
    {
        $equipe = Equipe::findOrFail($id);

        return $this->view('painel.equipe.edit', compact('equipe'));
    }

    public function update($id)
    {
        $equipe = Equipe::findOrFail($id);
        $input  = Input::all();

        $this->validation_rules['imagem'] = 'image';
        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            if (Input::hasFile('imagem')) {
                $input['imagem'] = CropImage::make('imagem', $this->image_config);
            } else {
                unset($input['imagem']);
            }

            $equipe->update($input);
            Session::flash('sucesso', 'Registro alterado com sucesso.');

            return Redirect::route('painel.equipe.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar registro.'])
                ->withInput();

        }
    }

    public function destroy($id)
    {
        try {

            Equipe::destroy($id);
            Session::flash('sucesso', 'Registro removido com sucesso.');

            return Redirect::route('painel.equipe.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover registro.']);

        }
    }

}

laravel/app/views/painel/pratica/_form.blade.php
@if($errors->any())
    @foreach($errors->all() as $error)
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ $error }}
    </div>
    @endforeach
@endif

@if(Session::has('sucesso'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ Session::get('sucesso') }}
    </div>
@endif

<div class="form-group">
    {{ Form::label('titulo_pt', 'Título [PORTUGUÊS]') }}
    {{ Form::text('titulo_pt', null, ['class' => 'form-control']) }}
</div>
<div class="form-group">
    {{ Form::label('texto_pt', 'Texto [PORTUGUÊS]') }}
    {{ Form::textarea('texto_pt', null, ['class' => 'form-control ckeditor', 'data-editor' => 'sub']) }}
</div>

<hr>

<div class="form-group">
    {{ Form::label('titulo_en', 'Título [INGLÊS]') }}
    {{ Form::text('titulo_en', null, ['class' => 'form-control']) }}
</div>
<div class="form-group">
    {{ Form::label('texto_en', 'Texto [INGLÊS]') }}
    {{ Form::textarea('texto_en', null, ['class' => 'form-control ckeditor', 'data-editor' => 'sub']) }}
</div>

<hr>

<div class="form-group">
    {{ Form::label('titulo_es', 'Título [ESPANHOL]') }}
    {{ Form::text('titulo_es', null, ['class' => 'form-control']) }}
</div>
<div class="form-group">
    {{ Form::label('texto_es', 'Texto [ESPANHOL]') }}
    {{ Form::textarea('texto_es', null, ['class' => 'form-control ckeditor', 'data-editor' => 'sub']) }}
</div>

{{ Form::submit($submitText, ['class' => 'btn btn-success']) }}

<a href="{{ route('painel.atuacao.pratica.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/app/views/painel/pratica/create.blade.php
@section('content')

    <legend>
        <h2><small>Prática Legal /</small> Adicionar Item</h2>
    </legend>

    {{ Form::open(['route' => 'painel.atuacao.pratica.store', 'files' => true]) }}

        @include('painel.pratica._form', ['submitText' => 'Inserir'])

    {{ Form::close() }}

@stop

laravel/app/views/painel/pratica/edit.blade.php
@section('content')

    <legend>
        <h2><small>Prática Legal /</small> Editar Item</h2>
    </legend>

    {{ Form::model($pratica, [
        'route' => ['painel.atuacao.pratica.update', $pratica->id],
        'method' => 'patch', 'files' => true])
    }}

        @include('painel.pratica._form', ['submitText' => 'Alterar'])

    {{ Form::close() }}

@stop

laravel/app/views/painel/pratica/index.blade.php
@section('content')

    @if($errors->any())
        @foreach($errors->all() as $error)
        <div class="alert alert-block alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ $error }}
        </div>
        @endforeach
    @endif

    @if(Session::has('sucesso'))
       <div class="alert alert-block alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ Session::get('sucesso') }}
        </div>
    @endif

    <legend>
        <h2>
            <small>Atuação /</small> Prática Legal
            <a href="{{ route('painel.atuacao.pratica.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Item</a>
        </h2>
    </legend>

    @if(count($pratica))
    <table class="table table-striped table-bordered table-hover table-sortable" data-tabela="pratica">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Título</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($pratica as $item)

            <tr class="tr-row" id="id_{{ $item->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td>{{ $item->titulo_pt }}</td>
                <td class="crud-actions">
                    {{ Form::open(array('route' => array('painel.atuacao.pratica.destroy', $item->id), 'method' => 'delete')) }}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.atuacao.pratica.edit', $item->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {{ Form::close() }}
                </td>
            </tr>

        @endforeach
        </tbody>
    </table>
    @else
        <div class="alert alert-warning" role="alert">Nenhum item cadastrado.</div>
    @endif

@stop